<a href="https://colab.research.google.com/github/valenmontechi/Big-Data/blob/main/EjerciciosPhyton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#ejercicio 1
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/fpineyro/homework-0/master/heart_disease.csv"

d_hd = pd.read_csv(url)

In [5]:
#ejercicio 2
print(d_hd.head())
print(d_hd.tail())

   age  gender  chest_pain  resting_blood_pressure  serum_cholestoral  \
0   63    male           1                     145                233
1   67    male           4                     160                286
2   67    male           4                     120                229
3   37    male           3                     130                250
4   41  female           2                     130                204

   fasting_blood_sugar  resting_electro  max_heart_rate  exer_angina  oldpeak  \
0                    1                2             150            0      2.3
1                    0                2             108            1      1.5
2                    0                2             129            1      2.6
3                    0                0             187            0      3.5
4                    0                2             172            0      1.4

   slope  num_vessels_flour  thal  heart_disease_severity  exter_angina  \
0      3                0.0   6.0                       0             0
1      2                3.0   3.0                       2             1
2      2                2.0   7.0                       1             1
3      3                0.0   3.0                       0             0
4      1                0.0   3.0                       0             0

  has_heart_disease
0                no
1               yes
2               yes
3                no
4                no
     age  gender  chest_pain  resting_blood_pressure  serum_cholestoral  \
298   45    male           1                     110                264
299   68    male           4                     144                193
300   57    male           4                     130                131
301   57  female           2                     130                236
302   38    male           3                     138                175

     fasting_blood_sugar  resting_electro  max_heart_rate  exer_angina  \
298                    0                0             132            0
299                    1                0             141            0
300                    0                0             115            1
301                    0                2             174            0
302                    0                0             173            0

     oldpeak  slope  num_vessels_flour  thal  heart_disease_severity  \
298      1.2      2                0.0   7.0                       1
299      3.4      2                2.0   7.0                       2
300      1.2      2                1.0   7.0                       3
301      0.0      2                1.0   3.0                       1
302      0.0      1                NaN   3.0                       0

     exter_angina has_heart_disease
298             0               yes
299             0               yes
300             1               yes
301             0               yes
302             0                no

In [6]:
#ejercicio 3
d_hd[['age', 'has_heart_disease']]

     age has_heart_disease
0     63                no
1     67               yes
2     67               yes
3     37                no
4     41                no
..   ...               ...
298   45               yes
299   68               yes
300   57               yes
301   57               yes
302   38                no

[303 rows x 2 columns]

In [7]:
#ejercicio 4
d_hd[d_hd['serum_cholestoral'] > 250]

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes
7,57,female,4,120,354,0,0,163,1,0.6,1,0.0,3.0,0,1,no
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes
11,56,female,2,140,294,0,2,153,0,1.3,2,0.0,3.0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,57,male,4,110,335,0,0,143,1,3.0,2,1.0,7.0,2,1,yes
281,47,male,3,130,253,0,0,179,0,0.0,1,0.0,3.0,0,0,no
285,58,male,4,114,318,0,1,140,0,4.4,3,3.0,6.0,4,0,yes
291,55,female,2,132,342,0,0,166,0,1.2,1,0.0,3.0,0,0,no
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes

In [9]:
#ejercicio 5 (no encontre libreria con la función status())
d_hd.isnull().sum()

age                       0
gender                    0
chest_pain                0
resting_blood_pressure    0
serum_cholestoral         0
fasting_blood_sugar       0
resting_electro           0
max_heart_rate            0
exer_angina               0
oldpeak                   0
slope                     0
num_vessels_flour         4
thal                      2
heart_disease_severity    0
exter_angina              0
has_heart_disease         0
dtype: int64

In [10]:
#ejercicio 6
d_hd['thal'] = d_hd['thal'].fillna(999)

In [11]:
#chequeo
d_hd['thal'].isnull().sum()

np.int64(0)

In [18]:
#ejercicio 7
d_hd[(d_hd['serum_cholestoral'] > 250) & (d_hd['age'] > 60)]

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes
32,64,male,3,140,335,0,0,158,0,0.0,1,0.0,3.0,1,0,yes
42,71,female,2,160,302,0,0,162,0,0.4,1,2.0,3.0,0,0,no
44,61,female,4,130,330,0,2,169,0,0.0,1,0.0,3.0,1,0,yes
48,65,female,3,140,417,1,2,157,0,0.8,1,1.0,3.0,0,0,no
70,65,female,3,155,269,0,0,148,0,0.8,1,0.0,3.0,0,0,no
71,67,male,4,125,254,1,0,163,0,0.2,2,2.0,7.0,3,0,yes
72,62,male,4,120,267,0,0,99,1,1.8,2,2.0,7.0,1,1,yes
75,65,female,3,160,360,0,2,151,0,0.8,1,0.0,3.0,0,0,no
83,68,male,3,180,274,1,2,150,1,1.6,2,0.0,7.0,3,1,yes
90,66,male,4,120,302,0,2,151,0,0.4,2,0.0,3.0,0,0,no
94,63,female,3,135,252,0,2,172,0,0.0,1,0.0,3.0,0,0,no
103,71,female,3,110,265,1,2,130,0,0.0,1,1.0,3.0,0,0,no
108,61,male,4,120,260,0,0,140,1,3.6,2,1.0,7.0,2,1,yes
110,61,female,4,145,307,0,2,146,1,1.0,2,0.0,7.0,1,1,yes
114,62,female,3,130,263,0,0,97,0,1.2,2,1.0,7.0,2,0,yes
118,63,male,4,130,330,1,2,132,1,1.8,1,3.0,7.0,3,1,yes
119,65,male,4,135,254,0,2,127,0,2.8,2,1.0,7.0,2,0,yes
121,63,female,4,150,407,0,2,154,0,4.0,2,3.0,7.0,4,0,yes
124,65,male,1,138,282,1,2,174,0,1.4,2,1.0,3.0,1,0,yes
137,62,male,2,120,281,0,2,103,0,1.4,2,1.0,7.0,3,0,yes
143,64,male,3,125,309,0,0,131,1,1.8,2,0.0,7.0,1,1,yes
152,67,female,3,115,564,0,2,160,0,1.6,2,0.0,7.0,0,0,no
155,70,male,4,130,322,0,2,109,0,2.4,2,3.0,3.0,1,0,yes
159,68,male,3,118,277,0,0,151,0,1.0,1,1.0,7.0,0,0,no
161,77,male,4,125,304,0,2,162,1,0.0,1,3.0,3.0,4,1,yes
170,70,male,3,160,269,0,0,112,1,2.9,2,1.0,7.0,3,1,yes
173,62,female,4,140,394,0,2,157,0,1.2,2,0.0,3.0,0,0,no
189,69,male,3,140,254,0,2,146,0,2.0,2,3.0,7.0,2,0,yes
193,62,female,4,138,294,1,0,106,0,1.9,2,3.0,3.0,2,0,yes
195,67,male,4,100,299,0,2,125,1,0.9,2,2.0,3.0,3,1,yes
201,64,female,4,180,325,0,0,154,1,0.0,1,0.0,3.0,0,1,no
203,64,female,3,140,313,0,0,133,0,0.2,1,0.0,7.0,0,0,no
218,64,female,4,130,303,0,0,122,0,2.0,2,2.0,3.0,0,0,no
224,63,female,4,108,269,0,0,169,1,1.8,2,2.0,3.0,1,1,yes
227,67,female,3,152,277,0,0,172,0,0.0,1,1.0,3.0,0,0,no
233,74,female,2,120,269,0,2,121,1,0.2,1,1.0,3.0,0,1,no
252,64,male,4,128,263,0,0,105,1,0.2,2,1.0,7.0,0,1,no
276,66,female,3,146,278,0,2,152,0,0.0,2,1.0,3.0,0,0,no

In [19]:
#ejercicio 8
d_hd['slope'].replace({1: 'ascendente', 2: 'descendente'})

0                3
1      descendente
2      descendente
3                3
4       ascendente
          ...
298    descendente
299    descendente
300    descendente
301    descendente
302     ascendente
Name: slope, Length: 303, dtype: object

In [20]:
#ejercicio 9
d_hd['is_healthy'] = d_hd['heart_disease_severity'] == 0

d_hd

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease,is_healthy
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no,True
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes,False
2,67,male,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1,1,yes,False
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no,True
4,41,female,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0,0,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes,False
299,68,male,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2,0,yes,False
300,57,male,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3,1,yes,False
301,57,female,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1,0,yes,False
302,38,male,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0,0,no,True

In [21]:
#ejercicio 10
d_hd_clean = d_hd.copy()

In [22]:
d_hd_clean = d_hd_clean.dropna()

In [23]:
d_hd_clean.isnull().sum()

age                       0
gender                    0
chest_pain                0
resting_blood_pressure    0
serum_cholestoral         0
fasting_blood_sugar       0
resting_electro           0
max_heart_rate            0
exer_angina               0
oldpeak                   0
slope                     0
num_vessels_flour         0
thal                      0
heart_disease_severity    0
exter_angina              0
has_heart_disease         0
is_healthy                0
dtype: int64